### ISSUE TITLE
Suggestion regarding cudnn subscription

### ISSUE THREAD

**Issue by Takaklas** [hadim/docker-tensorflow-builder#2]
Hello, your project is really nice and I would like to make it better by adding that you can surely download cudnn without the annoying subscription, within a script, from:
https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/
and then extract the .deb package using "dpkg-deb -x [debfile] [Extraction_folder]" command and the lib file .so will be in [Extraction_folder]/usr/lib/x86_64-linux-gnu/

**Comment by hadim** [comment]
I like the idea. What about licensing issue?

Would you submit a PR?

**Comment by hadim** [comment]
Done with https://github.com/hadim/docker-tensorflow-builder/commit/a99f020e23e04af271ddfa94a8324adb0470ac89
