### ISSUE TITLE
ERROR: Config value cuda is not defined in any .rc file

### ISSUE THREAD

**Issue by toby5box** [hadim/docker-tensorflow-builder#7]
I hit the following issue while using this project:
https://github.com/tensorflow/tensorflow/issues/23401

Perhaps the workaround there could be considered (or Bazel downgrade?)

**Comment by alexei-v-ivanov** [comment]
Same here. It is kind of frustrating to keep snagging time and time again over the trivial stuff.

Bazel guys, do you have any shame at all?

**Comment by sekarpdkt** [comment]
Are you able to build 1.11.0 or 1.12.0. When I tried 1.11.0, got into an issue referred here [https://github.com/tensorflow/tensorflow/issues/22583](https://github.com/tensorflow/tensorflow/issues/22583)

I selected nGraph (Y/n) as no.

I rerunning 1.12.0 with above fix as earlier attempts failed. Let me update later today about result. If any one of you were able to build it successfully, please let me know the options you selected for some of those build options asked.

**Comment by alexei-v-ivanov** [comment]
I was successful building latest with bazel 0.18 & following suggested options all the time.

**Comment by sekarpdkt** [comment]
Yes. I am also able to build it with following changes to build.sh

`conda install --yes numpy wheel bazel==0.18.1`

also added this post pulling from git

`# To handle bazel bug https://github.com/tensorflow/tensorflow/issues/23401#issuecomment-434690281

cat /tensorflow/tools/bazel.rc >> /tensorflow/.tf_configure.bazelrc`

**Comment by OlegSmelov** [comment]
According to https://www.tensorflow.org/install/source (see Tested build configurations), they build the latest TF version using Bazel 0.15.0. I think it's best to lock Bazel to that exact version.

**Comment by Peter9606** [comment]
> Yes. I am also able to build it with following changes to build.sh
> 
> `conda install --yes numpy wheel bazel==0.18.1`
> 
> also added this post pulling from git
> 
> `# To handle bazel bug [tensorflow/tensorflow#23401 (comment)](https://github.com/tensorflow/tensorflow/issues/23401#issuecomment-434690281)
> 
> cat /tensorflow/tools/bazel.rc >> /tensorflow/.tf_configure.bazelrc`

This works for me. Thank you!

**Comment by hadim** [comment]
You can now set the Bazel version before running the build (look on the README).
